# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api.proto.piratetreasure import piratetreasure_pb2 as api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2


class TreasureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTreasure = channel.unary_unary(
                '/api.proto.piratetreasure.TreasureService/ListTreasure',
                request_serializer=api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.ListTreasureRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.ListTreasureResponse.FromString,
                )
        self.GetTreasure = channel.unary_unary(
                '/api.proto.piratetreasure.TreasureService/GetTreasure',
                request_serializer=api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.GetTreasureRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.Treasure.FromString,
                )


class TreasureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTreasure(self, request, context):
        """return "Hello World"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTreasure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TreasureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTreasure': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTreasure,
                    request_deserializer=api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.ListTreasureRequest.FromString,
                    response_serializer=api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.ListTreasureResponse.SerializeToString,
            ),
            'GetTreasure': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTreasure,
                    request_deserializer=api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.GetTreasureRequest.FromString,
                    response_serializer=api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.Treasure.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.proto.piratetreasure.TreasureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TreasureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTreasure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.proto.piratetreasure.TreasureService/ListTreasure',
            api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.ListTreasureRequest.SerializeToString,
            api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.ListTreasureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTreasure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.proto.piratetreasure.TreasureService/GetTreasure',
            api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.GetTreasureRequest.SerializeToString,
            api_dot_proto_dot_piratetreasure_dot_piratetreasure__pb2.Treasure.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
