# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/proto/piratetreasure/piratetreasure.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/proto/piratetreasure/piratetreasure.proto',
  package='api.proto.piratetreasure',
  syntax='proto3',
  serialized_options=b'ZJgithub.com/netskope/piratetreasure/api/proto/piratetreasure;piratetreasure',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-api/proto/piratetreasure/piratetreasure.proto\x12\x18\x61pi.proto.piratetreasure\"B\n\x08Treasure\x12\x13\n\x0btreasure_id\x18\x01 \x01(\x03\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"L\n\x14ListTreasureResponse\x12\x34\n\x08treasure\x18\x01 \x03(\x0b\x32\".api.proto.piratetreasure.Treasure\")\n\x12GetTreasureRequest\x12\x13\n\x0btreasure_id\x18\x01 \x01(\x03\"#\n\x13ListTreasureRequest\x12\x0c\n\x04type\x18\x01 \x01(\t2\xe1\x01\n\x0fTreasureService\x12m\n\x0cListTreasure\x12-.api.proto.piratetreasure.ListTreasureRequest\x1a..api.proto.piratetreasure.ListTreasureResponse\x12_\n\x0bGetTreasure\x12,.api.proto.piratetreasure.GetTreasureRequest\x1a\".api.proto.piratetreasure.TreasureBLZJgithub.com/netskope/piratetreasure/api/proto/piratetreasure;piratetreasureb\x06proto3'
)




_TREASURE = _descriptor.Descriptor(
  name='Treasure',
  full_name='api.proto.piratetreasure.Treasure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='treasure_id', full_name='api.proto.piratetreasure.Treasure.treasure_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='api.proto.piratetreasure.Treasure.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='api.proto.piratetreasure.Treasure.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=141,
)


_LISTTREASURERESPONSE = _descriptor.Descriptor(
  name='ListTreasureResponse',
  full_name='api.proto.piratetreasure.ListTreasureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='treasure', full_name='api.proto.piratetreasure.ListTreasureResponse.treasure', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=219,
)


_GETTREASUREREQUEST = _descriptor.Descriptor(
  name='GetTreasureRequest',
  full_name='api.proto.piratetreasure.GetTreasureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='treasure_id', full_name='api.proto.piratetreasure.GetTreasureRequest.treasure_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=262,
)


_LISTTREASUREREQUEST = _descriptor.Descriptor(
  name='ListTreasureRequest',
  full_name='api.proto.piratetreasure.ListTreasureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='api.proto.piratetreasure.ListTreasureRequest.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=299,
)

_LISTTREASURERESPONSE.fields_by_name['treasure'].message_type = _TREASURE
DESCRIPTOR.message_types_by_name['Treasure'] = _TREASURE
DESCRIPTOR.message_types_by_name['ListTreasureResponse'] = _LISTTREASURERESPONSE
DESCRIPTOR.message_types_by_name['GetTreasureRequest'] = _GETTREASUREREQUEST
DESCRIPTOR.message_types_by_name['ListTreasureRequest'] = _LISTTREASUREREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Treasure = _reflection.GeneratedProtocolMessageType('Treasure', (_message.Message,), {
  'DESCRIPTOR' : _TREASURE,
  '__module__' : 'api.proto.piratetreasure.piratetreasure_pb2'
  # @@protoc_insertion_point(class_scope:api.proto.piratetreasure.Treasure)
  })
_sym_db.RegisterMessage(Treasure)

ListTreasureResponse = _reflection.GeneratedProtocolMessageType('ListTreasureResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTTREASURERESPONSE,
  '__module__' : 'api.proto.piratetreasure.piratetreasure_pb2'
  # @@protoc_insertion_point(class_scope:api.proto.piratetreasure.ListTreasureResponse)
  })
_sym_db.RegisterMessage(ListTreasureResponse)

GetTreasureRequest = _reflection.GeneratedProtocolMessageType('GetTreasureRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTREASUREREQUEST,
  '__module__' : 'api.proto.piratetreasure.piratetreasure_pb2'
  # @@protoc_insertion_point(class_scope:api.proto.piratetreasure.GetTreasureRequest)
  })
_sym_db.RegisterMessage(GetTreasureRequest)

ListTreasureRequest = _reflection.GeneratedProtocolMessageType('ListTreasureRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTTREASUREREQUEST,
  '__module__' : 'api.proto.piratetreasure.piratetreasure_pb2'
  # @@protoc_insertion_point(class_scope:api.proto.piratetreasure.ListTreasureRequest)
  })
_sym_db.RegisterMessage(ListTreasureRequest)


DESCRIPTOR._options = None

_TREASURESERVICE = _descriptor.ServiceDescriptor(
  name='TreasureService',
  full_name='api.proto.piratetreasure.TreasureService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=302,
  serialized_end=527,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListTreasure',
    full_name='api.proto.piratetreasure.TreasureService.ListTreasure',
    index=0,
    containing_service=None,
    input_type=_LISTTREASUREREQUEST,
    output_type=_LISTTREASURERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTreasure',
    full_name='api.proto.piratetreasure.TreasureService.GetTreasure',
    index=1,
    containing_service=None,
    input_type=_GETTREASUREREQUEST,
    output_type=_TREASURE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TREASURESERVICE)

DESCRIPTOR.services_by_name['TreasureService'] = _TREASURESERVICE

# @@protoc_insertion_point(module_scope)
