// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/proto/piratetreasure/piratetreasure.proto

package piratetreasure

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Treasure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TreasureId  int64  `protobuf:"varint,1,opt,name=treasure_id,json=treasureId,proto3" json:"treasure_id,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Treasure) Reset() {
	*x = Treasure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Treasure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Treasure) ProtoMessage() {}

func (x *Treasure) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Treasure.ProtoReflect.Descriptor instead.
func (*Treasure) Descriptor() ([]byte, []int) {
	return file_api_proto_piratetreasure_piratetreasure_proto_rawDescGZIP(), []int{0}
}

func (x *Treasure) GetTreasureId() int64 {
	if x != nil {
		return x.TreasureId
	}
	return 0
}

func (x *Treasure) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Treasure) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListTreasureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Treasure []*Treasure `protobuf:"bytes,1,rep,name=treasure,proto3" json:"treasure,omitempty"`
}

func (x *ListTreasureResponse) Reset() {
	*x = ListTreasureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTreasureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTreasureResponse) ProtoMessage() {}

func (x *ListTreasureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTreasureResponse.ProtoReflect.Descriptor instead.
func (*ListTreasureResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_piratetreasure_piratetreasure_proto_rawDescGZIP(), []int{1}
}

func (x *ListTreasureResponse) GetTreasure() []*Treasure {
	if x != nil {
		return x.Treasure
	}
	return nil
}

type GetTreasureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TreasureId int64 `protobuf:"varint,1,opt,name=treasure_id,json=treasureId,proto3" json:"treasure_id,omitempty"`
}

func (x *GetTreasureRequest) Reset() {
	*x = GetTreasureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTreasureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreasureRequest) ProtoMessage() {}

func (x *GetTreasureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreasureRequest.ProtoReflect.Descriptor instead.
func (*GetTreasureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_piratetreasure_piratetreasure_proto_rawDescGZIP(), []int{2}
}

func (x *GetTreasureRequest) GetTreasureId() int64 {
	if x != nil {
		return x.TreasureId
	}
	return 0
}

type ListTreasureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ListTreasureRequest) Reset() {
	*x = ListTreasureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTreasureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTreasureRequest) ProtoMessage() {}

func (x *ListTreasureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTreasureRequest.ProtoReflect.Descriptor instead.
func (*ListTreasureRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_piratetreasure_piratetreasure_proto_rawDescGZIP(), []int{3}
}

func (x *ListTreasureRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_api_proto_piratetreasure_piratetreasure_proto protoreflect.FileDescriptor

var file_api_proto_piratetreasure_piratetreasure_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x69, 0x72, 0x61,
	0x74, 0x65, 0x74, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x2f, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x65, 0x74, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x18, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x65, 0x74, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x22, 0x61, 0x0a, 0x08, 0x54, 0x72, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x72, 0x65, 0x61,
	0x73, 0x75, 0x72, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x56, 0x0a, 0x14,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x08, 0x74, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x70, 0x69, 0x72, 0x61, 0x74, 0x65, 0x74, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72,
	0x65, 0x2e, 0x54, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x52, 0x08, 0x74, 0x72, 0x65, 0x61,
	0x73, 0x75, 0x72, 0x65, 0x22, 0x35, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x61, 0x73,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72,
	0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x74, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x13, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x32, 0xe1, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x65, 0x61, 0x73,
	0x75, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x0c, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x12, 0x2d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x69, 0x72, 0x61, 0x74, 0x65, 0x74, 0x72, 0x65,
	0x61, 0x73, 0x75, 0x72, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x65, 0x61, 0x73, 0x75,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x69, 0x72, 0x61, 0x74, 0x65, 0x74, 0x72, 0x65, 0x61,
	0x73, 0x75, 0x72, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x54, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x69, 0x72, 0x61, 0x74, 0x65, 0x74, 0x72, 0x65, 0x61, 0x73,
	0x75, 0x72, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x70, 0x69, 0x72, 0x61, 0x74, 0x65, 0x74, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72,
	0x65, 0x2e, 0x54, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x74, 0x73, 0x6b, 0x6f, 0x70,
	0x65, 0x2f, 0x70, 0x69, 0x72, 0x61, 0x74, 0x65, 0x74, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x65, 0x74, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x3b, 0x70, 0x69, 0x72, 0x61, 0x74, 0x65,
	0x74, 0x72, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_piratetreasure_piratetreasure_proto_rawDescOnce sync.Once
	file_api_proto_piratetreasure_piratetreasure_proto_rawDescData = file_api_proto_piratetreasure_piratetreasure_proto_rawDesc
)

func file_api_proto_piratetreasure_piratetreasure_proto_rawDescGZIP() []byte {
	file_api_proto_piratetreasure_piratetreasure_proto_rawDescOnce.Do(func() {
		file_api_proto_piratetreasure_piratetreasure_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_piratetreasure_piratetreasure_proto_rawDescData)
	})
	return file_api_proto_piratetreasure_piratetreasure_proto_rawDescData
}

var file_api_proto_piratetreasure_piratetreasure_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_piratetreasure_piratetreasure_proto_goTypes = []interface{}{
	(*Treasure)(nil),             // 0: api.proto.piratetreasure.Treasure
	(*ListTreasureResponse)(nil), // 1: api.proto.piratetreasure.ListTreasureResponse
	(*GetTreasureRequest)(nil),   // 2: api.proto.piratetreasure.GetTreasureRequest
	(*ListTreasureRequest)(nil),  // 3: api.proto.piratetreasure.ListTreasureRequest
}
var file_api_proto_piratetreasure_piratetreasure_proto_depIdxs = []int32{
	0, // 0: api.proto.piratetreasure.ListTreasureResponse.treasure:type_name -> api.proto.piratetreasure.Treasure
	3, // 1: api.proto.piratetreasure.TreasureService.ListTreasure:input_type -> api.proto.piratetreasure.ListTreasureRequest
	2, // 2: api.proto.piratetreasure.TreasureService.GetTreasure:input_type -> api.proto.piratetreasure.GetTreasureRequest
	1, // 3: api.proto.piratetreasure.TreasureService.ListTreasure:output_type -> api.proto.piratetreasure.ListTreasureResponse
	0, // 4: api.proto.piratetreasure.TreasureService.GetTreasure:output_type -> api.proto.piratetreasure.Treasure
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_piratetreasure_piratetreasure_proto_init() }
func file_api_proto_piratetreasure_piratetreasure_proto_init() {
	if File_api_proto_piratetreasure_piratetreasure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Treasure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTreasureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTreasureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_piratetreasure_piratetreasure_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTreasureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_piratetreasure_piratetreasure_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_piratetreasure_piratetreasure_proto_goTypes,
		DependencyIndexes: file_api_proto_piratetreasure_piratetreasure_proto_depIdxs,
		MessageInfos:      file_api_proto_piratetreasure_piratetreasure_proto_msgTypes,
	}.Build()
	File_api_proto_piratetreasure_piratetreasure_proto = out.File
	file_api_proto_piratetreasure_piratetreasure_proto_rawDesc = nil
	file_api_proto_piratetreasure_piratetreasure_proto_goTypes = nil
	file_api_proto_piratetreasure_piratetreasure_proto_depIdxs = nil
}
